### ISSUE TITLE
hello!I meet a bug when run train.py could you please tell me how to fix it?

### ISSUE THREAD

**Issue by ANYMS-A** [hollance/TensorFlow-iOS-Example#1]
crissallandeMacBook-Pro:~ crissallan$ python3 train.py
Training set size: (2217, 20)
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "train.py", line 56, in <module>
    loss_value=sess.run(loss,feed_dict={x: X_train,y: y_train,regularization: 0})
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 903, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

**Comment by hollance** [comment]
That looks like maybe the line `loss_value=sess.run(loss,feed_dict={x: X_train,y: y_train,regularization: 0})` is placed outside the `with tf.Session() as sess:` block.
